on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running test process"

  report-success:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Success notification
        run: echo "Test succeeded - sending success notification"

  report-failure:
    needs: test
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Failure notification
        run: echo "Test failed - sending failure notification"
